load("//:custom_rules/pkg-config_rules/pkg-config.bzl","pkg_config_repository")

pkg_config_repository(
    name = "sdl2",
    modname="sdl2"
)

pkg_config_repository(
    name = "gl",
    modname="gl"
)

pkg_config_repository(
    name = "glew",
    modname="glew"
)

pkg_config_repository(
    name = "eigen3",
    modname="eigen3"
)

pkg_config_repository(
    name = "suitesparse",
    modname="suitesparse"
)

local_repository(
    name="pic_core",
    path="../pic-core",
)