cc_library(srcs = glob(["src/*.cpp"]),
	hdrs = glob(["include/pic_core.hpp"]),
	copts = ["-Iinclude"],
	strip_include_prefix = "include",
	visibility=["//visibility:public"],
	name="pic_core",
	deps=[])
