#load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
load("//:custom_rules/pkg-config_rules/pkg-config.bzl","pkg_config_repository")

pkg_config_repository(
    name = "eigen3",
    modname="eigen3"
)

local_repository(
    name="pic_core",
    path="pic-core",
)

pkg_config_repository(
    name = "suitesparse",
    modname="suitesparse"
)
